version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build
    commands:
      - echo Pre Build
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo Post Build
artifacts:
  files:
    - target/microservicedemo-0.0.1-SNAPSHOT.jar
  discard-paths: yes